package fe.fxsyncshare.composable.theme

import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFF89511E)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFFFDCC3)
val onPrimaryContainerLight = Color(0xFF2F1500)
val secondaryLight = Color(0xFF745944)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFFFDCC3)
val onSecondaryContainerLight = Color(0xFF2A1707)
val tertiaryLight = Color(0xFF5C6236)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFE1E7B0)
val onTertiaryContainerLight = Color(0xFF1A1E00)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF410002)
val backgroundLight = Color(0xFFFFF8F5)
val onBackgroundLight = Color(0xFF221A14)
val surfaceLight = Color(0xFFFFF8F5)
val onSurfaceLight = Color(0xFF221A14)
val surfaceVariantLight = Color(0xFFF3DFD2)
val onSurfaceVariantLight = Color(0xFF51443B)
val outlineLight = Color(0xFF847469)
val outlineVariantLight = Color(0xFFD6C3B6)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF382F28)
val inverseOnSurfaceLight = Color(0xFFFEEEE4)
val inversePrimaryLight = Color(0xFFFFB77E)
val surfaceDimLight = Color(0xFFE7D7CE)
val surfaceBrightLight = Color(0xFFFFF8F5)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFFFF1E9)
val surfaceContainerLight = Color(0xFFFBEBE1)
val surfaceContainerHighLight = Color(0xFFF5E5DB)
val surfaceContainerHighestLight = Color(0xFFEFDFD6)

val primaryDark = Color(0xFFFFB77E)
val onPrimaryDark = Color(0xFF4D2600)
val primaryContainerDark = Color(0xFF6C3A07)
val onPrimaryContainerDark = Color(0xFFFFDCC3)
val secondaryDark = Color(0xFFE3C0A6)
val onSecondaryDark = Color(0xFF422C1A)
val secondaryContainerDark = Color(0xFF5A422E)
val onSecondaryContainerDark = Color(0xFFFFDCC3)
val tertiaryDark = Color(0xFFC5CB96)
val onTertiaryDark = Color(0xFF2E330C)
val tertiaryContainerDark = Color(0xFF454A21)
val onTertiaryContainerDark = Color(0xFFE1E7B0)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF19120C)
val onBackgroundDark = Color(0xFFEFDFD6)
val surfaceDark = Color(0xFF19120C)
val onSurfaceDark = Color(0xFFEFDFD6)
val surfaceVariantDark = Color(0xFF51443B)
val onSurfaceVariantDark = Color(0xFFD6C3B6)
val outlineDark = Color(0xFF9E8E82)
val outlineVariantDark = Color(0xFF51443B)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFEFDFD6)
val inverseOnSurfaceDark = Color(0xFF382F28)
val inversePrimaryDark = Color(0xFF89511E)
val surfaceDimDark = Color(0xFF19120C)
val surfaceBrightDark = Color(0xFF413731)
val surfaceContainerLowestDark = Color(0xFF140D08)
val surfaceContainerLowDark = Color(0xFF221A14)
val surfaceContainerDark = Color(0xFF261E18)
val surfaceContainerHighDark = Color(0xFF312822)
val surfaceContainerHighestDark = Color(0xFF3C332C)


